### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by fjremnav** [mrebol/f2f-consistent-semantic-segmentation#1]
Do you plan to release training code?

Thanks,
FJ

**Comment by mrebol** [comment]
Hi FJ,

At the moment I do not plan to upload training code.

**Comment by fjremnav** [comment]
Manuel

     Thanks for the response of the training code relase.
I ran a longer sequence (my own clip)  of evaluation (test) using 
python eval.py --config config/eval.yml 

Results seem OK initially, but it is getting very bad after more than 100 frames.
Do you have any idea why this happens?
Do you have segmentation results with a much longer clip, like more than 300 frames which you can share?

Thanks,
FJ

**Comment by mrebol** [comment]
The trained model I provide was optimized for the Cityscapes sequences consisting of 30 frames.
If you want to use this model I would recommend that you reinitialize the
cell and the hidden state of the LSTM cell after 30 frames to achieve the best results.
